export default {
    about_us:'Quienes Somos?',
    contact_details:'Detalles de contacto',
    email:'Email :',
    phone:'Teléfono :',
    driver_account_approve_err:'Su cuenta aún no está aprobada como conductor.',
    account_not_exsist:'Su cuenta no existe como conductor.',
    driver_ride_complete_status:' El conductor ha completado su viaje. tu ID de reserva es',
    please_wait:'Calculando tu tarifa',
    on_trip:'Viaje en curso',
    complete_trip:'Finalizar Viaje',
    account_successful_done:'Su cuenta se ha creado con éxito y está esperando la confirmación de aprobación por parte del administrador.',
    image_size_error:'El tamaño de la imagen no debe ser superior a 12 MB.',
    password_blank_error:'La contraseña no puede estar en blanco.',
    password_complexity_alphabet:'La contraseña debe constar de al menos 1 carácter alfanumérico y una longitud de 8 a 15.',
    password_complexity_complex:'La contraseña debe tener al menos 1 letra mayúscula, 1 letra minúscula, 1 dígito y 1 carácter especial con una longitud de 6 a 10.',
    driver_registration:'Registro de conductor',
    first_name:'Nombre(s)',
    first_name_error:'Por favor, introduzca su nombre(s)',
    last_name:'Apelidos',
    last_name_error:'Por favor ingrese su apellido',
    email:'Email',
    email_blank_error:'Por favor, introduce una dirección de correo electrónico válida',
    mobile:'Número de teléfono',
    mobile_no_blank_error:'Ingrese el número de celular',
    password:'Contraseña',
    confrim_password:'Confirmar contraseña',
    password_not_match:'Las contraseñas no coinciden',
    vehicle_model_name:'Nombre del modelo del vehículo',
    vehicle_model_name_blank_error:'El nombre del vehículo no puede estar en blanco',
    vehicle_reg_no:'Matrícula del vehículo',
    vehicle_number_blank_err:'El número de vehículo no puede estar en blanco',
    upload_driving_lisence:'Cargue su licencia de conducir',
    image_size_warning:'(Tamaño de imagen: Max 12 MB)',
    reg_no:'Registrar Ahora',
    update_profile:'Actualizar Perfil',
    valid_mobile_number:'Por favor, introduzca un número de móvil válido',
    update_now:'Actualizar ahora',
    no_notification:'No se encontró ninguna notificación',
    forgot_password:'Olvidaste tu contraseña?',
    valid_email_err:'Por favor, introduce una dirección de correo electrónico válida',
    send_email:'Enviar email',
    enter_code:'Introduzca el código',
    submit:'Enviar',
    change_password:'Cambiar contraseña ?',
    old_password:'Contraseña anterior',
    old_password_err:'Ingrese la contraseña anterior',
    new_password:'Nueva contraseña',
    new_password_err:'Ingrese una nueva contraseña',
    update:'Actualizar',
    login:'Iniciar Sesión',
    booking_request:'Solicitudes de Viajes',
    profile_settings:'Mi Perfil',
    incomeText:"Mis Comisiones",
    my_bookings:'Mis Reservas',
    about_us:'Quienes Somos?',
    sign_out:'Cerrar Sesión',
    rider_ride_cancel_text:'El usuario canceló el viaje',
    mobile_no_found:'Número de teléfono no encontrado',
    otp_error:'Ingrese el código OTP correcto',
    driver_journey_err:'El conductor inició su viaje. tu ID de reserva es',
    on_trip:'Viaje en curso',
    wait_for_rider:'Esperando Usuario',
    rider_notified:'El usuario ha sido notificado',
    start_trip:'INICIAR VIAJE',
    cancel_reson_1:'No se pudo contactar con el conductor',
    cancel_reson_2:'El Auto no se movio en dirección del usuario',
    cancel_reson_3:'La razón no está en la lista',
    cancel_reson_4:'Conductor se nego',
    cancel_reson_5:'El conductor está tardando mucho',
    api_error:'Google places API Error',
    accept_booking_request:'Acepte su solicitud de Servicio',
    pickup_location:'Lugar de recogida',
    drop_location:'Destino',
    ignore_text:'Ignorar',
    modal_close:'Se ha cerrado modal.',
    alert_text:'Atención',
    ignore_job_title:'¿Quieres ignorar este Viaje??',
    cancel:'Cancelar',
    ok:'OK',
    accept:'Aceptar',
    task_list:'Lista de Viajes',
    rider_not_here:'Actualmente no hay solicitudes en su área',
    booking_request_rejected:'Su solicitud de reserva ha sido rechazada por el conductor solicitado',
    driver_requested_for_payment:'El conductor ha solicitado el pago. tu ID de reserva es',
    request_payment:'SOLICITAR PAGO',
    my_rides:'Mis Viajes',
    password_reset_link:'Un enlace de restablecimiento de contraseña se a enviado a su correo electrónico, verifique y restablezca su nueva contraseña.',
    notification:'Notificaciones',
    chat_blank:'Escribe tu mensaje ...',
    send_msg:', te envió un mensaje: \n',
    driver:'Conuctor',
    chat_history_not_found:'No se encontró historial de chat',
    chat:'Chat',
    send:'Enviar',
    type_messege:'Escriba su mensaje',
    photo_upload_action_sheet_title:'Elija una imagen ?',
    camera:'Camara',
    galery:'Galeria',
    cancel:'Cancelar',
    yes:'Sí',
    password_change:'Tu contraseña se actualizó correctamente',
    password_not_match:'las contraseñas no coinciden',
    confrim:'Esta acción eliminará tu cuenta',
    delete_account:'Quieres eliminar tu cuenta ?',
    my_profile:'Perfil',
    active_status:'Estatus activo',
    profile_details:'Detalles del perfil',
    location:'Ubicación',
    mobile_no:'Número de teléfono',
    preffered_lang:'Idioma',
    lang:'Español',
    delete_account:'¿Quieres eliminar tu cuenta?',
    payment_info:'Información de pago del pasajero',
    booking_details:'Detalle de mis reservas',
    you_rate_text:'Has sido calificado',
    no_rated_text:'No tienes calificación',
    bill_details:'Detalles de la factura',
    your_trip:'Tu viaje',
    total_bill:'Cuenta total',
    include_tax:'Incluye todos los impuestos',
    total_payable:'Mi Ganancia',
    go_to_booking:'Ver detalles del viaje',
    my_booking:'Mis Reservas',
    job_ignore:'¿Quieres ignorar este Servicio??',
    show_modal:'Mostrar modal',
    notification_title:'Uder Notificación',
    register:'Registrarse',
    today:'Ganancias de hoy',
    thismonth:'Ganancias de este mes',
    totalearning:'Ganancia total',
    convenienceFee:'Costo administrativo',
    paymentStatus:'Estatus del pago',
    payment_mode:'Metodo de pago',
    customer_payable:'Pago del Usuario',
    discount_amount:'Descuento',
    CardPaymentAmount:'Pagar con tarjeta -',
    CashPaymentAmount:'Pagar en efectivo -',
    WalletPayment:'Pagar con billetera -',
    android_channel: 'Notificaciones Uder'
}